### ISSUE TITLE
Updating :username throughout

### ISSUE THREAD

**Issue by artificialarea** [jcochran206/artsy-capstone-client#29]
Re: EditProfile.js 

If username is updated in EditProfile, the two instances of`:username` referenced in the Nav and in the URL `/profile/:username` doesn't update unless one logs out and logs in again. 

Perhaps some context or some sort of `useContext` hook is required? If you know the solution, perhaps you could give it a try?

**Comment by bateman001** [comment]
Just fixed this with an updateUsername function in user-service. It saves the new username in the local storage. Then instead of `history.push.goBack()`. I replaced it with `history.push(`profile/${user.username}`}` so that it changes the url and then is able to update everything else from there

**Comment by artificialarea** [comment]
I belatedly noticed that the EditProfile caused an error if the updated `:username` was unique. Sorry about that. It must have given you problems with the work you were doing. Resolved the wee issue on the server and committed. Git pull the latest version of server and all should be well.
